name: Build E-Book

on:
  push:
    branches:
      - main
permissions:
  contents: write
  actions: read
  pull-requests: read
jobs:
  convert:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Debug - List Files in Repository
        run: ls -R  # 🔍 Mengecek apakah template.tex ada di repo

      - name: Install Pandoc
        run: sudo apt-get install -y pandoc texlive-xetex
        
      - name: Create Pandoc Template Directory
        run: mkdir -p ~/.local/share/pandoc/templates/

      - name: Copy Custom LaTeX Template
        run: cp ebook/template.tex ~/.local/share/pandoc/templates/

      - name: Convert Markdown to PDF
        run: pandoc ebook/*.md -s -o ebook/logika_perbatasan.pdf --pdf-engine=xelatex --template=template.tex

      - name: Convert Markdown to EPUB
        run: pandoc ebook/*.md -s -o ebook/logika_perbatasan.epub --toc --css=style.css

      - name: Upload PDF & EPUB to Repository
        uses: actions/upload-artifact@v4
        with:
          name: E-Book Logika Perbatasan
          path: ebook/logika_perbatasan.*


      - name: Commit & Push PDF ke Repository (PAT)
        env:
          PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git checkout main
          git pull origin main
          git add ebook/logika_perbatasan.pdf
          git add ebook/logika_perbatasan.epub
          git commit -m "Menambahkan versi terbaru e-book"
          git push https://x-access-token:${{ secrets.PAT_TOKEN }}@github.com/Raviyanto/logika-perbatasan.git HEAD:main
